name: Build Resume PDF

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Build site
        run: bundle exec jekyll build
      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf
      - name: Start local server
        run: |
          python3 -m http.server 8000 --directory _site &
          echo $! > server.pid
          sleep 2
      - name: Generate PDF
        run: wkhtmltopdf http://localhost:8000/index.html resume.pdf
      - name: Stop local server
        run: kill $(cat server.pid)
      - name: Commit PDF
        uses: EndBug/add-and-commit@v9
        with:
          add: "resume.pdf"
          message: "chore: update resume.pdf"
          default_author: github_actions
          push: true
